apiVersion: v1
kind: List
items:
- apiVersion: v1
  data:
    broker.password: cmVkc3Rhcg==
    broker.user: YWRtaW4=
    keystore.password: cGFzc3dvcmQ=
    truststore.password: cGFzc3dvcmQ=
  kind: Secret
  metadata:
    name: broker-credentials
  type: Opaque
- apiVersion: v1
  data:
    broker.ks: MIIJiwIBAzCCCUQGCSqGSIb3DQEHAaCCCTUEggkxMIIJLTCCBWkGCSqGSIb3DQEHAaCCBVoEggVWMIIFUjCCBU4GCyqGSIb3DQEMCgECoIIE+zCCBPcwKQYKKoZIhvcNAQwBAzAbBBRq5QECFIWnJHB3rZxycBkPuEWvDAIDAMNQBIIEyDeQtxX4glDeEXQaGnmwZqBIKWhG09IRwHm/7ZEKHiUIt3OdDp86DI92RUXRL6zxtNdCXDetQ2YXzsesjxePZFNgdieJHzpFC3ZimyEFzKUSdxmx4yhu6HDGSiBcf/YYPG53rk8ENQTS+pDI1WF74+4626CeGRhJx4sEjIMz/7YVwkFMrGQVthcOoKX0zAMxH5tp5XVa8IULOx2JXkF17dBdJkjlglUvsYylt7x1IPcbwyr6sC6RxwDNADO4uFBQjNOYkV4FyKz29KrIMenDwcRrhCL1p2mrkYV2DbGzkf7fnxm2FyD86+qaKEbCG1xxncabl1ZqMKWZIrE88rVehlZMEsfrIUnF+5w4f7wkEGjLhjIX4U7PL512s388DwIxQqo+fWpzBn8hcMzKzfcCZwji6OTJACDqiYHQiPvaOqThtp/U5WLbFezbvdLGHwBc69+iPvDY55Tj12VnJZ7EuEm2nqRNtdt0/Im2yIrx0bnZ6yZlTw91Kiuq8hgaXsH08DaEIm6uiFgKvv31f42mls9ScWM3AREckZOrJVIQAU8N2oEocemCdWvZePPNiNSTwm08O+VNNXEr8SCLnk/epBwc54D3xEW2f3wYCzzSzq6expHdnk19ix+UQFWiS+B4PqyKjQWGXlWeWOms+zreFQe3csw8Yujznr+UbVDl5JnuM0TJSVeiV9PXv+jdlS4kcmDHKTHMxmzFtTbna6/uuZq32mJsFrdR1rM27tGe7zaE4gXY/NIC01Cb9egwRHDnePg8jrRRImYVkHcqQGiwkCPJNtubCMT5QcFfe/oT7LGcQmoSorBdwNTSdN0VCQVINtqqU0ktjD3E+HTeQNIsIK+RA2/dDqRSIeI0jmMaW9JCtmZnLHeLXzvehAcXKTdlErlMjDXr+iEG7W8UQjA3Tju3Wnv2zni3HqrrUst75OCLSjQ3GwT8nTH1QvH0a+jr9OVAYXbYW258lStkJc5dGb4NIXgrWZw+nJInJj27ao6Zb5Pw/zLsqr/jnlwrnsw4uh0ui+E8N2j7pFv38eGyfjLchB46Qh9QBHQcJ7kmTg+WLL+pflBUH9LP/X9BQDXKWL3K8ktJO/MSrbdHphhUjknJJcq9ziTEP8ebxyvD2kQeNSO/2sle6wb+d9IjlJUO0rVDMCQ5C8fNRsQ68aVEbn4qivCQ3qfb2+fO4+ikW4pnovPr1PpJGsELwz/C3bHfjKTyr9iVl2cApTYzjOd/7w0TQgnADk/ERoCkrx9Mw/lo7vfiUVlR5cvVu+Zt1C725oiuI7GadOKrxVjtlCtTXzZV1zXN5tfZYlpeLUNeH7V5X2CSMe7CyVKgDzNtMdvqh4TzIa153RxxQBNDxVBgHfjcyEIxEjFEzKg9Cyg9CZb62mFNJbEkA9THfYsDkFO44vaEJvN6XV2olKPpxhcXvgboiZpkydpdO8pHbyE05npCOtqtj/uLyCVpZUnoZt9QrH4DpHT3oF0KQ+d4N3/Z9x2RZnn97d32WNN9O0fFAPR9oomRYeB6w2+pdhAIV5n62qtFypLnuDvkTyeQBlA5pNq9p/KCyR79Z3fVhjWckK1Z9TrRGyFfQ5IEcayzFAa1qToPTJqBZSOxWaidNRdKxisq8YqwVbQ0bzFAMBsGCSqGSIb3DQEJFDEOHgwAYgByAG8AawBlAHIwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTU4ODA2ODQxODkwODCCA7wGCSqGSIb3DQEHBqCCA60wggOpAgEAMIIDogYJKoZIhvcNAQcBMCkGCiqGSIb3DQEMAQYwGwQUyPBGA9889DCzve8RBrQ6kJS37J4CAwDDUICCA2gagDNPlD+KtH81zKm/mBtED9pNgw4VnhvqJWgL+QqeAtUmVoTIwYVFNUGAvAO8ylQdhoratrJo3RoX5ei9CgasEmYAkYAMRou4sP/5yv99YKLC0S9fUFtH1tS3IbHHCk1RKBQroC6/Oytqpgbf3931+AJXq2XsHjgYshjVPj7gZgT3PzPv4xxPXcoViIcr8556yHUFeoLh5DHsf62mH5Tr/Hf9W/yWKMcbGJGpTvX7/0nlJXYh6VBDrn4jzH6jpqeu8nutEpjKKLzxFburu83wcKJmsv6DGvwIrmKyJcPD0g976kj4UMkXfMBbwUmtxk6rHX2uOzV6t4T/zfU0VT0HaJhJzHHA93qqLga5bZQL7OwMLw+vTQjMbJgbYb8g24Fdv8H/t5RW6U5Q6w1mEv/4ZokDgbn4LHBYEcyuSgQBChykcoKxL90disDPTnNEJElQgucN9wbMye3QFwAO9EMntLZjtv5o//pzDJnJeLCXvFzWh4gl485993isCGY5DGtCNCnBKxuQyJkkM26u6gwT2k9OtnO93IgtJ81ScbATZZTfAZylGRVcy+kY9bpzGcrIojQpNZCnhB1ZZ8XrbSHQ99uLWtEgXqF3/75Dnz1EGzCaA3dqhV4MRxB4+tLiB5Fnnlea8YiUAuHdmcaxFkuDyBAIdELdH5XljnVkLMI8AoeB3SkgcrciektNlS4wYFOk0KrhiASFrDM18/h/cY4QVYJdaTL/XRljR3V1UbaSY1ZvFjYvQUodxquJzpHvO8wpgKpTMjUS1QG5WPrcaTu9+OB9/7r4k1Y3wXf+31JLm4u8lL0fvpyuGaRd04uCted+YwU211uAHQ2h9t3hH1NTwbP7Sy49wzbgd4Sh4UyTiT3oXDOkqrMOczpd3hpsyBPqyJTOxW5IPGiFFnQEfQordA2aLNSEDIwpdF9d44owM1a+vRkd49e//GQEPdk3BkGY4i/yHuholYFPCuLm0vRZ5HhmgQ2MATHMjW2F1/MQh9K4tw62thPkCqezkeJcU+vOoPGwrOfTQWBq3XsgSbJM61Tb78fLaU8DANmNrLmBuXgZIeC7gSbpT6cTAxRyp6IACQPPv82tWhUzbC1ZESHHlRUFaAhdqyVWZiccUNV3vQ8Z7AY0YUPZ3YlxKbYPRk9kSf+qPgcHJTA+MCEwCQYFKw4DAhoFAAQUcDLpM1cE8wLXJzWSRTjIuRBOitkEFPQ8SEbQlf+q0lsHYRazWohFXF5dAgMBhqA=
    broker.ts: /u3+7QAAAAIAAAABAAAAAgAGY2xpZW50AAABccBBC74ABVguNTA5AAAC7TCCAukwggHRoAMCAQICBBmo0tgwDQYJKoZIhvcNAQELBQAwJTESMBAGA1UEBxMJR2ltbWVydG9uMQ8wDQYDVQQDEwZjbGllbnQwHhcNMjAwNDI4MTAwNjU5WhcNMjAwNzI3MTAwNjU5WjAlMRIwEAYDVQQHEwlHaW1tZXJ0b24xDzANBgNVBAMTBmNsaWVudDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAIRt4vfLRuQ6pQ+s17sZPQmJwuDl54x9hbLqcqvpxJ9wxrwWOx0HgX+cZ+BCRmz+RL+gGAcUbnP5JYtDwjOYRyJhGxwEZrtlH1pHn3rWP+hKKUwz64qGDmbykiz6t2VjQGVVC0GpdRQMl88I1XgBApOXh8VWZDpCbE585uF+v8Pg0x136eaCT5bWPfDSz/0BqDpgDuUQDjziqFS60TffeR/hT6o1Fxzb/U/qKk3OHnfzCRCgQDitrXmMuqU0/H0KQXI+l9mIBVcx5JUiORPXGUuABqBzI+RhMlsTvCoopixYB5xiedDnRJOYUs0gjuSeUGpF5lTo2GqAaZwex+CvCVkCAwEAAaMhMB8wHQYDVR0OBBYEFNLvgvQYgZTkrGsAwJMgPXnqpYAuMA0GCSqGSIb3DQEBCwUAA4IBAQBOdqZfRpTU9ziWgPoI7HPYT15dO9OJvjxYcXzmcQYtPJWpxFqn7BA7mlu3YFE49n619FKUht5/IFd/jxz74lJTXS7o7wijxpvXjak3vvPpUhLEG4KLVgd/sGdQAeDTI2LvUexniaw6AslX3/K0oM3OPeNx6iNEJJ/qe8z/fEZBGLZ0zqqa+il79osz2cBrPWQVvrNiHkz6ViPrPYh+2QfIHvDE23jAIiZmGa9xg+DNZ2/aYeVNZhNKx9PMnJj4O86f9L4/WnM2pibxMFIMPksDEPLKCzYNf4bTknsyOsnHVB5iPr0xOti30MWM1q3Ei8XYKZiX5H6eIU4qxnzWJ1lqGIDV0yaoX1VfNg5PaJa4ds+e4OQ=
  kind: Secret
  metadata:
    labels:
      application: broker
    name: broker-keystores
  type: Opaque
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: broker-config
  data:
    broker.xml: |-
      <?xml version='1.0'?>
      <!--
      Licensed to the Apache Software Foundation (ASF) under one
      or more contributor license agreements.  See the NOTICE file
      distributed with this work for additional information
      regarding copyright ownership.  The ASF licenses this file
      to you under the Apache License, Version 2.0 (the
      "License"); you may not use this file except in compliance
      with the License.  You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing,
      software distributed under the License is distributed on an
      "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
      KIND, either express or implied.  See the License for the
      specific language governing permissions and limitations
      under the License.
      -->

      <configuration xmlns="urn:activemq"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xmlns:xi="http://www.w3.org/2001/XInclude"
                     xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">

         <core xmlns="urn:activemq:core" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="urn:activemq:core ">

            <name>${AMQ_NAME}</name>


            <persistence-enabled>true</persistence-enabled>

            <!-- this could be ASYNCIO, MAPPED, NIO
                 ASYNCIO: Linux Libaio
                 MAPPED: mmap files
                 NIO: Plain Java Files
             -->
            <journal-type>NIO</journal-type>

            <paging-directory>/opt/amq/data/paging</paging-directory>

            <bindings-directory>/opt/amq/data/bindings</bindings-directory>

            <journal-directory>/opt/amq/data/journal</journal-directory>

            <large-messages-directory>/opt/amq/data/large-messages</large-messages-directory>

            <journal-datasync>true</journal-datasync>

            <journal-min-files>2</journal-min-files>

            <journal-pool-files>10</journal-pool-files>

            <journal-device-block-size>4096</journal-device-block-size>

            <journal-file-size>10M</journal-file-size>

            <!--
             This value was determined through a calculation.
             Your system could perform 0.02 writes per millisecond
             on the current journal configuration.
             That translates as a sync write every 62363999 nanoseconds.

             Note: If you specify 0 the system will perform writes directly to the disk.
                   We recommend this to be 0 if you are using journalType=MAPPED and journal-datasync=false.
            -->
            <journal-buffer-timeout>62363999</journal-buffer-timeout>


            <!--
              When using ASYNCIO, this will determine the writing queue depth for libaio.
             -->
            <journal-max-io>1</journal-max-io>
            <!--
              You can verify the network health of a particular NIC by specifying the <network-check-NIC> element.
               <network-check-NIC>theNicName</network-check-NIC>
              -->

            <!--
              Use this to use an HTTP server to validate the network
               <network-check-URL-list>http://www.apache.org</network-check-URL-list> -->

            <!-- <network-check-period>10000</network-check-period> -->
            <!-- <network-check-timeout>1000</network-check-timeout> -->

            <!-- this is a comma separated list, no spaces, just DNS or IPs
                 it should accept IPV6

                 Warning: Make sure you understand your network topology as this is meant to validate if your network is valid.
                          Using IPs that could eventually disappear or be partially visible may defeat the purpose.
                          You can use a list of multiple IPs, and if any successful ping will make the server OK to continue running -->
            <!-- <network-check-list>10.0.0.1</network-check-list> -->

            <!-- use this to customize the ping used for ipv4 addresses -->
            <!-- <network-check-ping-command>ping -c 1 -t %d %s</network-check-ping-command> -->

            <!-- use this to customize the ping used for ipv6 addresses -->
            <!-- <network-check-ping6-command>ping6 -c 1 %2$s</network-check-ping6-command> -->




            <!-- how often we are looking for how many bytes are being used on the disk in ms -->
            <disk-scan-period>5000</disk-scan-period>

            <!-- once the disk hits this limit the system will block, or close the connection in certain protocols
                 that won't support flow control. -->
            <max-disk-usage>90</max-disk-usage>

            <!-- should the broker detect dead locks and other issues -->
            <critical-analyzer>true</critical-analyzer>

            <critical-analyzer-timeout>120000</critical-analyzer-timeout>

            <critical-analyzer-check-period>60000</critical-analyzer-check-period>

            <critical-analyzer-policy>HALT</critical-analyzer-policy>


            <page-sync-timeout>62363999</page-sync-timeout>


                  <!-- the system will enter into page mode once you hit this limit.
                 This is an estimate in bytes of how much the messages are using in memory

                  The system will use half of the available memory (-Xmx) by default for the global-max-size.
                  You may specify a different value here if you need to customize it to your needs.

                  <global-max-size>100Mb</global-max-size>

            -->

            <acceptors>

               <!-- useEpoll means: it will use Netty epoll if you are on a system (Linux) that supports it -->
               <!-- amqpCredits: The number of credits sent to AMQP producers -->
               <!-- amqpLowCredits: The server will send the # credits specified at amqpCredits at this low mark -->
               <!-- amqpDuplicateDetection: If you are not using duplicate detection, set this to false
                                            as duplicate detection requires applicationProperties to be parsed on the server. -->

               <!-- Note: If an acceptor needs to be compatible with HornetQ and/or Artemis 1.x clients add
                          "anycastPrefix=jms.queue.;multicastPrefix=jms.topic." to the acceptor url.
                          See https://issues.apache.org/jira/browse/ARTEMIS-1644 for more information. -->

               <!-- Acceptor for every supported protocol -->
               <acceptor name="artemis">tcp://0.0.0.0:61616?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=CORE,AMQP,STOMP,HORNETQ,MQTT,OPENWIRE;useEpoll=true;amqpCredits=1000;amqpLowCredits=300;amqpDuplicateDetection=true</acceptor>

               <!-- AMQP Acceptor.  Listens on default AMQP port for AMQP traffic.-->
               <acceptor name="amqp">tcp://0.0.0.0:5672?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=AMQP;useEpoll=true;amqpCredits=1000;amqpLowCredits=300;amqpDuplicateDetection=true</acceptor>

               <!-- STOMP Acceptor. -->
               <acceptor name="stomp">tcp://0.0.0.0:61613?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=STOMP;useEpoll=true</acceptor>

               <!-- HornetQ Compatibility Acceptor.  Enables HornetQ Core and STOMP for legacy HornetQ clients. -->
               <acceptor name="hornetq">tcp://0.0.0.0:5445?anycastPrefix=jms.queue.;multicastPrefix=jms.topic.;protocols=HORNETQ,STOMP;useEpoll=true</acceptor>

               <!-- MQTT Acceptor -->
               <acceptor name="mqtt">tcp://0.0.0.0:1883?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=MQTT;useEpoll=true</acceptor>

                  <acceptor name="artemis-ssl">tcp://0.0.0.0:61617?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=CORE,AMQP,STOMP,HORNETQ,MQTT,OPENWIRE;useEpoll=true;amqpCredits=1000;amqpLowCredits=300;connectionsAllowed=1000;sslEnabled=true;keyStorePath=/etc/amq-secret-volume/broker.ks;keyStorePassword=password</acceptor>
                  <acceptor name="amqp-ssl">tcp://0.0.0.0:5671?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=AMQP;useEpoll=true;amqpCredits=1000;amqpMinCredits=300;connectionsAllowed=1000;sslEnabled=true;keyStorePath=/etc/amq-secret-volume/broker.ks;keyStorePassword=password</acceptor>
                  <acceptor name="stomp-ssl">tcp://0.0.0.0:61612?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=STOMP;useEpoll=true;connectionsAllowed=1000;sslEnabled=true;keyStorePath=/etc/amq-secret-volume/broker.ks;keyStorePassword=password</acceptor>
                  <acceptor name="mqtt-ssl">tcp://0.0.0.0:8883?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=MQTT;useEpoll=true;connectionsAllowed=1000;sslEnabled=true;keyStorePath=/etc/amq-secret-volume/broker.ks;keyStorePassword=password</acceptor>

            </acceptors>


            <security-settings>
               <security-setting match="#">
                  <permission type="createNonDurableQueue" roles="admin"/>
                  <permission type="deleteNonDurableQueue" roles="admin"/>
                  <permission type="createDurableQueue" roles="admin"/>
                  <permission type="deleteDurableQueue" roles="admin"/>
                  <permission type="createAddress" roles="admin"/>
                  <permission type="deleteAddress" roles="admin"/>
                  <permission type="consume" roles="admin"/>
                  <permission type="browse" roles="admin"/>
                  <permission type="send" roles="admin"/>
                  <!-- we need this otherwise ./artemis data imp wouldn't work -->
                  <permission type="manage" roles="admin"/>
               </security-setting>
            </security-settings>

            <address-settings>
               <!-- if you define auto-create on certain queues, management has to be auto-create -->
               <address-setting match="activemq.management#">
                  <dead-letter-address>DLQ</dead-letter-address>
                  <expiry-address>ExpiryQueue</expiry-address>
                  <redelivery-delay>0</redelivery-delay>
                  <!-- with -1 only the global-max-size is in use for limiting -->
                  <max-size-bytes>-1</max-size-bytes>
                  <message-counter-history-day-limit>10</message-counter-history-day-limit>
                  <address-full-policy>PAGE</address-full-policy>
                  <auto-create-queues>true</auto-create-queues>
                  <auto-create-addresses>true</auto-create-addresses>
                  <auto-create-jms-queues>true</auto-create-jms-queues>
                  <auto-create-jms-topics>true</auto-create-jms-topics>
               </address-setting>
               <!--default for catch all-->
               <address-setting match="#">
                  <dead-letter-address>DLQ</dead-letter-address>
                  <expiry-address>ExpiryQueue</expiry-address>
                  <redelivery-delay>0</redelivery-delay>
                  <!-- with -1 only the global-max-size is in use for limiting -->
                  <max-size-bytes>-1</max-size-bytes>
                  <message-counter-history-day-limit>10</message-counter-history-day-limit>
                  <address-full-policy>PAGE</address-full-policy>
                  <auto-create-queues>true</auto-create-queues>
                  <auto-create-addresses>true</auto-create-addresses>
                  <auto-create-jms-queues>true</auto-create-jms-queues>
                  <auto-create-jms-topics>true</auto-create-jms-topics>
               </address-setting>
            </address-settings>

            <addresses>
               <address name="DLQ">
                  <anycast>
                     <queue name="DLQ" />
                  </anycast>
               </address>
               <address name="ExpiryQueue">
                  <anycast>
                     <queue name="ExpiryQueue" />
                  </anycast>
               </address>
               <address name="acme.foods.egg">
                  <anycast>
                     <queue name="acme.foods.egg" />
                  </anycast>
               </address>
               <address name="acme.foods.bacon">
                  <anycast>
                     <queue name="acme.foods.bacon" />
                  </anycast>
               </address>

            </addresses>


            <!-- Uncomment the following if you want to use the Standard LoggingActiveMQServerPlugin pluging to log in events
            <broker-plugins>
               <broker-plugin class-name="org.apache.activemq.artemis.core.server.plugin.impl.LoggingActiveMQServerPlugin">
                  <property key="LOG_ALL_EVENTS" value="true"/>
                  <property key="LOG_CONNECTION_EVENTS" value="true"/>
                  <property key="LOG_SESSION_EVENTS" value="true"/>
                  <property key="LOG_CONSUMER_EVENTS" value="true"/>
                  <property key="LOG_DELIVERING_EVENTS" value="true"/>
                  <property key="LOG_SENDING_EVENTS" value="true"/>
                  <property key="LOG_INTERNAL_EVENTS" value="true"/>
               </broker-plugin>
            </broker-plugins>
            -->

         </core>
      </configuration>
