apiVersion: v1
kind: Template
parameters:
- name: ZONE_NAME
  displayName: Zone Name
  description: Suffix to add to the objects' names to ensure their uniqueness
  required: true
- name: NODE_SELECTOR_KEY
  displayName: Affinity Node Selector Key
  description: Key to use to find nodes on which to schedule the broker pods (Affinity scheduling)
  required: true
- name: NODE_SELECTOR_VALUE
  displayName: Affinity Node Selector Value
  description: Value to use to find nodes on which to schedule the broker pods (Affinity scheduling)
  required: true
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: inter-router-${ZONE_NAME}
  data:
    qdrouterd.conf: |-
      router {
          mode: interior
          id: Router.${HOSTNAME}
      }

      #log {
      #    module: SERVER
      #    enable: trace+
      #    includeTimestamp: yes
      #}

      # only allow anonymous connections over localhost
      listener {
          host: localhost
          port: amqp
          authenticatePeer: no
          saslMechanisms: ANONYMOUS
      }

      listener {
          host: 0.0.0.0
          port: amqps
          role: normal
          sslProfile: external
          authenticatePeer: yes
          requireSsl: true
          saslMechanisms: PLAIN
      }

      listener {
          host: 0.0.0.0
          port: 55672
          role: inter-router
          sslProfile: inter_router_tls
          authenticatePeer: yes
          requireSsl: true
          saslMechanisms: EXTERNAL
      }

      sslProfile {
          name: inter_router_tls
          certFile: /etc/qpid-dispatch-certs/inter-router/tls.crt
          privateKeyFile: /etc/qpid-dispatch-certs/inter-router/tls.key
          caCertFile: /etc/qpid-dispatch-certs/inter-router/ca.crt
      }

      sslProfile {
          name: external
          certFile: /etc/qpid-dispatch-certs/external/tls.crt
          privateKeyFile: /etc/qpid-dispatch-certs/external/tls.key
      }

      listener {
          host: 0.0.0.0
          port: 8672
          authenticatePeer: yes
          http: true
          httpRootDir: /usr/share/qpid-dispatch/console
      }

      address {
          prefix: closest
          distribution: closest
      }

      address {
          prefix: multicast
          distribution: multicast
      }

      address {
          prefix: unicast
          distribution: closest
      }

      address {
          prefix: exclusive
          distribution: closest
      }

      address {
          prefix: broadcast
          distribution: multicast
      }

      # Note - the connection to the intra-router is initiated by the intra-router itself

      address {
          prefix: acme.foods
          waypoint: yes
          distribution: closest
      }

      policy {
          enableVhostPolicy: true
          enableVhostNamePatterns: true
          defaultVhost: $default
          policyDir: /etc/qpid-policies
      }

      # Connect to the router in each zone
      connector {
          role: inter-router
          host: inter-router-aztec
          port: 55672
          sslProfile: inter_router_tls
          verifyHostname: false
      }

      connector {
          role: inter-router
          host: inter-router-medieval
          port: 55672
          sslProfile: inter_router_tls
          verifyHostname: false
      }

      connector {
          role: inter-router
          host: inter-router-industrial
          port: 55672
          sslProfile: inter_router_tls
          verifyHostname: false
      }
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: inter-router-${ZONE_NAME}
    name: inter-router-${ZONE_NAME}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentConfig: inter-router-${ZONE_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 0
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          application: inter-router-${ZONE_NAME}
          deploymentConfig: inter-router-${ZONE_NAME}
        name: inter-router-${ZONE_NAME}
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: ${NODE_SELECTOR_KEY}
                  operator: In
                  values:
                  - ${NODE_SELECTOR_VALUE}
        containers:
        - env:
          - name: APPLICATION_NAME
            value: inter-router-${ZONE_NAME}
          - name: QDROUTERD_CONF
            value: /etc/qpid-dispatch/qdrouterd.conf
          - name: QDROUTERD_AUTO_MESH_DISCOVERY
            value: QUERY
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          image: registry.redhat.io/amq7/amq-interconnect:1.7
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8672
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: inter-router-${ZONE_NAME}
          ports:
          - containerPort: 5672
            name: amqp
            protocol: TCP
          - containerPort: 5671
            name: amqps
            protocol: TCP
          - containerPort: 8672
            name: http
            protocol: TCP
          - containerPort: 55672
            name: inter
            protocol: TCP
          - containerPort: 45672
            name: edge
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8672
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/qpid-dispatch-certs/inter-router/
            name: inter-router-certs
            readOnly: true
          - mountPath: /etc/qpid-dispatch-certs/external/
            name: external-certs
            readOnly: true
          - mountPath: /etc/qpid-dispatch/
            name: config-volume
          - mountPath: /etc/qpid-policies/
            name: policies-volume
          - mountPath: /etc/sasl2/
            name: sasl-config
          - mountPath: /etc/sasldb/
            name: sasl-db
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: router
        serviceAccountName: router
        terminationGracePeriodSeconds: 60
        volumes:
        - name: inter-router-certs
          secret:
            defaultMode: 420
            secretName: router-inter-router-certs
        - name: external-certs
          secret:
            defaultMode: 420
            secretName: router-external-certs
        - name: sasl-config
          configMap:
            defaultMode: 420
            name: router-sasl-config
        - name: sasl-db
          secret:
            defaultMode: 420
            secretName: router-sasl-db
        - name: config-volume
          configMap:
            defaultMode: 420
            name: inter-router-${ZONE_NAME}
        - name: policies-volume
          configMap:
            defaultMode: 420
            name: router-policies
    test: false
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The router's AMQP port.
    labels:
      application: inter-router-${ZONE_NAME}
    name: inter-router-${ZONE_NAME}
  spec:
    ports:
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: amqps
      port: 5671
      protocol: TCP
      targetPort: 5671
    - name: http
      port: 8672
      protocol: TCP
      targetPort: 8672
    - name: inter-router
      port: 55672
      protocol: TCP
      targetPort: 55672
    - name: edge
      port: 45672
      protocol: TCP
      targetPort: 45672
    selector:
      deploymentConfig: inter-router-${ZONE_NAME}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      application: inter-router-${ZONE_NAME}
    name: inter-router-${ZONE_NAME}-console
  spec:
    port:
      targetPort: http
    tls:
      termination: edge
    to:
      kind: Service
      name: inter-router-${ZONE_NAME}
- kind: Route
  apiVersion: v1
  metadata:
    name: inter-router-${ZONE_NAME}
    labels:
      application: inter-router-${ZONE_NAME}
  spec:
    port:
      targetPort: amqps
    tls:
      termination: passthrough
    to:
      kind: Service
      name: inter-router-${ZONE_NAME}
